"use client";
import {useEffect,useState} from 'react';
import {motion,useReducedMotion} from 'framer-motion';
import {CarFront,Minus,Plus,ArrowRight,Check,Pause,Play,MapPin} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Phone,pick} from './interactive';
export function Reveal({children,className=''}:{children:React.ReactNode;className?:string}){const reduced=useReducedMotion();return <motion.div className={className} initial={{opacity:0,y:reduced?0:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:.6}}>{children}</motion.div>}
export function RideDemo({ar}:{ar:boolean}){
 const cars=[['Taxi','تاكسي',12,18],['Comfort','كومفورت',14,21],['Executive','تنفيذي',18,27],['Family','عائلي',15,22.5]] as const;
 const [selected,setSelected]=useState(0);const [fare,setFare]=useState(12);const [sent,setSent]=useState(false);
 return <div className="ride-demo"><div className="demo-top"><span><MapPin size={16}/>{pick(ar,'Jeddah · Your next stop','جدة · وجهتك القادمة')}</span><span className="demo-badge">{pick(ar,'INTERACTIVE DEMO','تجربة توضيحية')}</span></div><div className="ride-options" role="group" aria-label={pick(ar,'Choose your ride','اختر مشوارك')}>{cars.map(([en,arabic,min,max],i)=><button key={en} className={selected===i?'selected':''} aria-pressed={selected===i} onClick={()=>{setSelected(i);setFare(min);setSent(false)}}><CarFront/><span><strong>{pick(ar,en,arabic)}</strong><small>{pick(ar,'Choose your comfort','اختر ما يناسبك')}</small></span><b dir="ltr">SAR {min}–{max}</b>{selected===i&&<Check size={16}/>}</button>)}</div><div className="offer-box"><div><strong>{pick(ar,'Your offer','عرضك')}</strong><small>{pick(ar,'A price that works for you','السعر اللي يناسبك')}</small></div><div className="fare-control"><button aria-label={pick(ar,'Decrease fare','خفض السعر')} disabled={fare<=cars[selected][2]} onClick={()=>{setFare(fare-1);setSent(false)}}><Minus size={18}/></button><output aria-live="polite" dir="ltr">SAR {fare.toFixed(2)}</output><button aria-label={pick(ar,'Increase fare','زيادة السعر')} disabled={fare>=cars[selected][3]} onClick={()=>{setFare(Math.min(fare+1,cars[selected][3]));setSent(false)}}><Plus size={18}/></button></div><button className="button" onClick={()=>setSent(true)}>{pick(ar,'Try an offer','جرّب تقديم عرض')}<ArrowRight size={18}/></button><p className="demo-result" aria-live="polite">{sent?pick(ar,`Example response: a driver suggests SAR ${(fare+2).toFixed(2)}. Review offers and choose in the app.`,`رد توضيحي: يقترح سائق ${(fare+2).toFixed(2)} ر.س. راجع العروض واختر داخل التطبيق.`):pick(ar,'Illustration only. Fares and driver availability vary.','للتوضيح فقط. تختلف الأسعار وتوفّر السائقين.')}</p></div></div>
}
const screens=['rides','services','activities','home'] as const;
export function Showcase({ar}:{ar:boolean}){
 const [active,setActive]=useState('rides');const [auto,setAuto]=useState(false);const reduced=useReducedMotion();
 useEffect(()=>{if(!auto||reduced)return;const timer=setInterval(()=>setActive(v=>screens[(screens.indexOf(v as typeof screens[number])+1)%4]),6000);return()=>clearInterval(timer)},[auto,reduced]);
 const labels=ar?['المشاوير','الخدمات','الأنشطة','الرئيسية']:['Rides','Services','Activities','Home'];
 const titles=ar?['مشوارك يبدأ باختيارك.','المساعدة أقرب مما تتخيل.','كل حجوزاتك، في مكان واحد.','يومك كله يبدأ من هنا.']:['Your next move, on your terms.','A helping hand, close to home.','Your plans. All in one place.','Your everyday starts here.'];
 const descriptions=ar?['اختر نوع السيارة، اقترح سعرك، واطّلع على عروض السائقين.','تصفح الخدمات واعثر على المحترفين المناسبين لطلبك.','تابع تفاصيل حجوزاتك ومواعيدها وحالتها من شاشة الأنشطة.','اكتشف المشاوير والخدمات والورود والهدايا من شاشة واحدة.']:['Choose a vehicle, suggest your fare, and explore offers from nearby drivers.','Browse service categories and discover professionals for your request.','Keep booking details, dates and statuses together in your Activities screen.','Discover rides, services, flowers and gifts from one familiar home screen.'];
 return <section className="showcase section" id="app"><div className="container"><div className="section-heading"><div><div className="eyebrow">{pick(ar,'A CLOSER LOOK','نظرة أقرب')}</div><h2>{pick(ar,'See OrderUp in action.','تعرّف على OrderUp عن قرب.')}</h2></div><p>{pick(ar,'One familiar app. So many ways to make the day your own.','تطبيق واحد مألوف، وطرق كثيرة ليصير يومك على كيفك.')}</p></div><Tabs value={active} onValueChange={v=>{setActive(v);setAuto(false)}} dir={ar?'rtl':'ltr'}><TabsList className="showcase-tabs">{screens.map((s,i)=><TabsTrigger key={s} value={s}>{labels[i]}</TabsTrigger>)}</TabsList>{screens.map((s,i)=><TabsContent value={s} key={s}><div className="showcase-layout"><div className="showcase-copy"><span className="large-number">0{i+1}</span><h3>{titles[i]}</h3><p>{descriptions[i]}</p><a className="inline-link" href="#download">{pick(ar,'Make it part of your day','خلّه جزء من يومك')}<ArrowRight size={17}/></a><div className="progress-bars">{screens.map((x,j)=><span className={i===j?'active':''} key={x}/>)}</div></div><motion.div className="showcase-device" initial={{opacity:.4}} animate={{opacity:1}}><Phone screen={s}/><div className="screen-caption">{pick(ar,'ACTUAL ORDERUP APP SCREEN','من تطبيق OrderUp الفعلي')}</div></motion.div></div></TabsContent>)}</Tabs><button className="autoplay" onClick={()=>setAuto(!auto)} aria-pressed={auto}>{auto?<Pause size={14}/>:<Play size={14}/>} {pick(ar,auto?'Pause preview':'Play preview',auto?'إيقاف العرض':'تشغيل العرض')}</button></div></section>
}
export function HowItWorks({ar}:{ar:boolean}){
 const [flow,setFlow]=useState('rides');const [step,setStep]=useState(0);
 const data=ar?{rides:['اختر مشوارك','اقترح سعرك','استقبل العروض','انطلق'],services:['اختر الخدمة','أضف تفاصيل طلبك','اكتشف مقدمي الخدمة','احجز'],gifts:['اختر الهدية','أضف بيانات المستلم','أكّد الطلب','إلى من تحب']}:{rides:['Choose your ride','Suggest your fare','Receive offers','Get going'],services:['Choose a service','Tell us what you need','Discover providers','Make a booking'],gifts:['Choose something special','Add your recipient','Place your order','Send a little joy']};
 const notes=ar?{rides:['حدد موقعك ووجهتك ونوع السيارة.','قدّم عرض سعر يناسب مشوارك.','راجع العروض المتاحة من السائقين.','اختر العرض المناسب وأكمل التفاصيل داخل التطبيق.'],services:['تصفح الخدمات المنزلية واختر ما تحتاجه.','أجب عن الأسئلة وأضف موقع الخدمة.','اطّلع على مقدمي الخدمة القريبين منك.','راجع التفاصيل وأكمل الحجز داخل التطبيق.'],gifts:['تصفح الورود والهدايا المتاحة.','أضف اسم المستلم وعنوان التوصيل.','راجع تفاصيل الطلب قبل تأكيده.','تابع تفاصيل طلبك داخل التطبيق.']}:{rides:['Set your pickup, destination and preferred vehicle.','Put forward a fare that works for your journey.','Explore responses from available nearby drivers.','Choose an offer and confirm the details in the app.'],services:['Explore the categories and choose the help you need.','Answer a few questions and set the service location.','Explore nearby professionals for your request.','Review the details and complete your booking in the app.'],gifts:['Explore the available flowers and gifts.','Add the recipient and their delivery address.','Review your order details before confirming.','Follow your order details in the app.']};
 const key=flow as keyof typeof data;
 return <section className="section" id="how-it-works"><div className="container"><div className="center-heading"><div className="eyebrow">{pick(ar,'LESS EFFORT. MORE EVERYDAY.','خطوات أقل. حياة أسهل.')}</div><h2>{pick(ar,'From “need to” to done.','من قائمة المهام إلى تمّ.')}</h2></div><Tabs value={flow} onValueChange={v=>{setFlow(v);setStep(0)}} dir={ar?'rtl':'ltr'}><TabsList className="flow-tabs">{['rides','services','gifts'].map((s,i)=><TabsTrigger value={s} key={s}>{(ar?['المشاوير','الخدمات','الورود والهدايا']:['Rides','Services','Flowers & gifts'])[i]}</TabsTrigger>)}</TabsList><TabsContent value={flow}><div className="steps">{data[key].map((title,i)=><button key={title} aria-pressed={step===i} onClick={()=>setStep(i)} className={step===i?'active':''}><span>0{i+1}</span><strong>{title}</strong><ArrowRight size={18}/></button>)}</div><div className="step-detail" aria-live="polite"><span>0{step+1}</span><div><h3>{data[key][step]}</h3><p>{notes[key][step]}</p></div></div></TabsContent></Tabs></div></section>
}
export function FAQ({ar}:{ar:boolean}){
 const questions=ar?['ما هو OrderUp؟','ما الخدمات التي يمكنني حجزها؟','كيف يعمل نظام عروض أسعار المشاوير؟','ما الخدمات المنزلية المتاحة؟','هل يمكنني إرسال الورود أو الهدايا لشخص آخر؟','أين تتوفر خدمات OrderUp؟','كيف أنضم كسائق؟','كيف أنضم كمقدم خدمة؟','هل التطبيق متاح لآيفون وأندرويد؟']:['What is OrderUp?','What can I book through OrderUp?','How does ride bidding work?','What home services are available?','Can I send flowers or gifts to someone else?','Where is OrderUp available?','How do I become an OrderUp driver?','How can I become a service provider?','Is OrderUp available on iPhone and Android?'];
 const answers=ar?['OrderUp يجمع المشاوير والخدمات المنزلية والورود والهدايا في تجربة واحدة لحياتك اليومية.','يمكنك حجز المشاوير والتاكسي والخدمات المنزلية وطلب الورود والهدايا. تحقق داخل التطبيق من المتاح في موقعك.','اختر نوع السيارة واقترح سعرك، ثم راجع عروض السائقين المتاحة. الأسعار وتوفّر السائقين وقبول العروض تختلف.','تشمل التنظيف والسباكة والكهرباء والنجارة والأقفال والصيانة والتركيب والإصلاحات والمساج، بحسب المتاح في موقعك.','نعم، يمكنك اختيار الورود أو الهدايا وإضافة بيانات الشخص الذي تريد إرسالها إليه.','OrderUp مصمم للحياة اليومية في السعودية، مع التركيز على جدة. تحقق من التطبيق لمعرفة الخدمات المتاحة في موقعك.','تعرّف على تطبيق OrderUp Driver من صفحة السائقين. تفاصيل التسجيل ستتوفر عبر القنوات الرسمية.','تعرّف على تطبيق OrderUp Service Providers من صفحة مقدمي الخدمات. تفاصيل الانضمام ستتوفر عبر القنوات الرسمية.','نعم، وفقًا لمعلومات المنتج، التطبيق متاح على iOS وAndroid. ستُضاف روابط المتاجر الرسمية هنا عند توفرها.']:['OrderUp brings rides, home services, flowers and gifts together in one connected experience for everyday life.','Book rides and taxis, discover home services, and order flowers and gifts. Check the app for what is available at your location.','Choose your vehicle and suggest a fare, then review responses from available drivers. Prices, driver availability and acceptance can vary.','Categories include cleaning, plumbing, electrical work, carpentry, locks, maintenance, installation, repairs and massage, subject to availability.','Yes. Choose flowers or gifts and add the recipient’s details to send something thoughtful to someone else.','OrderUp is designed for everyday life in Saudi Arabia, with a focus on Jeddah. Check the app for services available at your location.','Explore the dedicated OrderUp Driver app on our driver page. Registration details will be available through official channels.','Explore OrderUp Service Providers on our provider page. Joining details will be available through official channels.','Yes, the product is available on iOS and Android. Official store links will be added here when supplied.'];
 return <section className="section faq" id="faq"><div className="container faq-grid"><div><div className="eyebrow">{pick(ar,'GOOD TO KNOW','كل ما يهمك')}</div><h2>{pick(ar,'A few things you might be wondering.','إجابات لأسئلتك.')}</h2><p>{pick(ar,'A little clarity before your first OrderUp.','تعرّف على المزيد قبل تجربتك الأولى.')}</p></div><Accordion type="single" collapsible>{questions.map((q,i)=><AccordionItem value={`q${i}`} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{answers[i]}{i===6&&<a className="inline-link" href={`/${ar?'ar':'en'}/driver/`}>{pick(ar,'For drivers','للسائقين')} →</a>}{i===7&&<a className="inline-link" href={`/${ar?'ar':'en'}/providers/`}>{pick(ar,'For providers','لمقدمي الخدمات')} →</a>}</AccordionContent></AccordionItem>)}</Accordion></div></section>
}
