"use client";
import {useEffect,useState} from 'react';
import Image from 'next/image';
import {motion,useReducedMotion} from 'framer-motion';
import {ArrowUpRight,ArrowRight,CarFront,MapPin,Menu,Download,Play,Check,Smartphone} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription,SheetTrigger,SheetClose} from '@/components/ui/sheet';
import {config} from '@/lib/orderup/config';
export const pick=(ar:boolean,en:string,arabic:string)=>ar?arabic:en;
export function Wordmark(){return <span className="wordmark" dir="ltr"><Image src="/images/orderup-logo.png" alt="OrderUp" width={1329} height={405} sizes="160px" priority/></span>}
export function Navbar({ar,page=''}:{ar:boolean;page?:string}){
 const [scrolled,setScrolled]=useState(false);
 useEffect(()=>{const handler=()=>setScrolled(window.scrollY>24);handler();window.addEventListener('scroll',handler,{passive:true});return()=>window.removeEventListener('scroll',handler)},[]);
 const links=[['home','Home','الرئيسية'],['services','Services','الخدمات'],['rides','Rides','المشاوير'],['how-it-works','How it works','كيف يعمل'],['drivers','For partners','للشركاء']];
 return <><a className="skip" href="#main">{pick(ar,'Skip to content','انتقل إلى المحتوى')}</a><header className={`nav ${scrolled?'scrolled':''}`}><div className="nav-inner"><a aria-label="OrderUp" href={`/${ar?'ar':'en'}/#home`}><Wordmark/></a><nav className="desktop-nav" aria-label={pick(ar,'Main navigation','التنقل الرئيسي')}>{links.map(([id,en,arabic])=><a key={id} href={`/${ar?'ar':'en'}/#${id}`}>{pick(ar,en,arabic)}</a>)}</nav><div className="nav-actions"><a className="language" href={`/${ar?'en':'ar'}/${page?`${page}/`:''}`} onClick={e=>{e.preventDefault();window.location.href=`/${ar?'en':'ar'}/${page?`${page}/`:''}${window.location.hash}`}}>{ar?'English':'العربية'}</a><a className="button small nav-download" href="#download">{pick(ar,'Get the app','حمّل التطبيق')}<ArrowUpRight size={16}/></a><Sheet><SheetTrigger className="mobile-menu" aria-label={pick(ar,'Open menu','افتح القائمة')}><Menu/></SheetTrigger><SheetContent side={ar?'left':'right'} className="menu-panel"><SheetTitle><Wordmark/></SheetTitle><SheetDescription>{pick(ar,'More for your everyday.','كل ما تحتاجه ليومك.')}</SheetDescription>{links.map(([id,en,arabic])=><SheetClose asChild key={id}><a href={`/${ar?'ar':'en'}/#${id}`}>{pick(ar,en,arabic)}<ArrowUpRight/></a></SheetClose>)}<SheetClose asChild><a className="button" href="#download">{pick(ar,'Download OrderUp','حمّل OrderUp')}</a></SheetClose></SheetContent></Sheet></div></div></header></>;
}
export function Phone({screen,className='',priority=false}:{screen:keyof typeof config.images;className?:string;priority?:boolean}){return <div className={`phone ${className}`}><div className="camera"/><Image src={config.images[screen]} width={738} height={1600} alt={`OrderUp ${screen} app screen`} priority={priority} sizes="(max-width:600px) 180px,280px"/></div>}
export function StoreButtons({ar,audience}:{ar:boolean;audience?:'driver'|'providers'}){const urls=audience?config.partnerApps[audience]:{ios:config.APP_STORE_URL,android:config.GOOGLE_PLAY_URL};return <div className="store-buttons">{[['App Store',urls.ios,'iOS'],['Google Play',urls.android,'Android']].map(([name,url,platform])=><a className="store" key={name} href={url||'#download-info'} aria-label={`${name} — ${url?pick(ar,'Download','تحميل'):pick(ar,'Coming soon','قريبًا')}`} {...(url?{target:'_blank',rel:'noopener noreferrer'}:{'aria-describedby':'download-info'})}><Smartphone aria-hidden="true"/><span><small>{url?pick(ar,`Download for ${platform}`,`حمّل لـ ${platform}`):pick(ar,`${platform} · Coming soon`,`${platform} · قريبًا`)}</small>{name}</span></a>)}</div>}
export function Hero({ar}:{ar:boolean}){
 const reduced=useReducedMotion();const [pointer,setPointer]=useState({x:0,y:0});
 return <section className="hero" id="home"><div className="container hero-grid"><motion.div className="hero-copy" initial={{opacity:0,y:reduced?0:22}} animate={{opacity:1,y:0}} transition={{duration:.65}}><div className="eyebrow"><span className="location-dot"/>{pick(ar,'JEDDAH’S EVERYDAY APP','تطبيقك لكل يوم في جدة')}</div><h1>{pick(ar,'More for your','كل ما تحتاجه')}<br/><span>{pick(ar,'everyday.','ليومك.')}</span></h1><p>{pick(ar,'Rides, home services, flowers, gifts and more. A little less to do. A lot more to enjoy.','مشاوير، خدمات منزلية، ورود وهدايا وأكثر. مهام أقل، ووقت أكثر للي تحب.')}</p><div className="hero-ctas"><a className="button" href="#download">{pick(ar,'Download OrderUp','حمّل OrderUp')}<Download size={18}/></a><a className="text-button" href="#how-it-works"><span className="play"><Play size={13} fill="currentColor"/></span>{pick(ar,'See how it works','شاهد كيف يعمل')}</a></div><div className="hero-platform"><Smartphone size={16}/>{pick(ar,'Made for your day. Available on iOS & Android.','مصمم ليومك. متاح على iOS وAndroid.')}</div></motion.div><motion.div className="hero-art" onMouseMove={e=>{if(reduced||window.innerWidth<900)return;const r=e.currentTarget.getBoundingClientRect();setPointer({x:(e.clientX-r.left-r.width/2)/45,y:(e.clientY-r.top-r.height/2)/55})}} onMouseLeave={()=>setPointer({x:0,y:0})} animate={{x:pointer.x,y:pointer.y}} transition={{type:'spring',stiffness:70,damping:22}}><div className="hero-oval"/><span className="orbit-label">{pick(ar,'ONE APP. MORE POSSIBILITIES.','تطبيق واحد. إمكانيات أكثر.')}</span><motion.div className="device devices-back" initial={{opacity:0,y:reduced?0:45}} animate={{opacity:1,y:0}} transition={{delay:.3,duration:.8}}><Phone screen="services" priority/></motion.div><motion.div className="device devices-ride" initial={{opacity:0,y:reduced?0:60}} animate={{opacity:1,y:0}} transition={{delay:.15,duration:.8}}><Phone screen="rides" priority/></motion.div><motion.div className="device devices-main" initial={{opacity:0,y:reduced?0:75}} animate={{opacity:1,y:0}} transition={{duration:.8}}><Phone screen="home" priority/></motion.div><div className="floating-chip ride-chip"><span><CarFront/></span><div><small>{pick(ar,'YOUR RIDE. YOUR PRICE.','مشوارك. بسعرك.')}</small><strong>{pick(ar,'You’re in the driving seat','أنت تختار السعر')}</strong></div><ArrowUpRight size={18}/></div><div className="floating-chip booked-chip"><span><Check/></span><div><strong>{pick(ar,'Everyday, taken care of','يومك صار أسهل')}</strong><small>{pick(ar,'All together in OrderUp','كلها في OrderUp')}</small></div></div></motion.div></div><div className="container hero-bottom"><span><MapPin size={15}/>{pick(ar,'A little more Jeddah. A lot more you.','من جدة، ليومك.')}</span><a href="#services">{pick(ar,'Explore your everyday','اكتشف المزيد')}<ArrowRight size={17}/></a></div></section>
}
