import Image from 'next/image';
import {ArrowRight, ArrowUpRight, CarFront, Wrench, Clock3, MapPin, Gift, Check, Wallet, Smartphone, Sparkles, BadgeCheck, ChevronDown} from 'lucide-react';
import {Navbar, StoreButtons} from './interactive';

type Partner = 'driver' | 'providers';
const pick = (ar: boolean, en: string, arabic: string) => ar ? arabic : en;

export function PartnerSection({ar}: {ar: boolean}) {
 const t = (en: string, arabic: string) => pick(ar, en, arabic);
 return <section className="partner-hub section" id="drivers"><div className="container">
  <div className="section-heading"><div><div className="eyebrow">{t('YOUR NEXT CHAPTER STARTS HERE', 'خطوتك القادمة تبدأ هنا')}</div><h2>{t('More opportunity.', 'فرص أكثر.')}<br/><em>{t('With OrderUp.', 'مع OrderUp.')}</em></h2></div><p>{t('Take the wheel or bring your expertise. Turn what you do into new opportunities, with a dedicated app built around your work.', 'انطلق بسيارتك أو قدّم خبرتك. حوّل مهاراتك إلى فرص جديدة، مع تطبيق مخصص لطبيعة عملك.')}</p></div>
  <div className="partner-cards">{(['driver', 'providers'] as const).map(kind => {
   const driver = kind === 'driver'; const Icon = driver ? CarFront : Wrench;
   return <article className={`partner-card ${kind}`} key={kind} id={driver ? undefined : 'providers'}>
    <div className="partner-card-image"><Image src={driver ? '/images/driver-cover.webp' : '/images/home-service.webp'} alt={driver ? t('Driver beside a car in Jeddah', 'سائق بجانب سيارة في جدة') : t('Professional carrying out home maintenance', 'محترف يقدم خدمة صيانة منزلية')} width={1440} height={960} sizes="(max-width: 700px) 100vw, 50vw"/><span className="partner-photo-label"><Icon size={16}/>{driver ? t('FOR DRIVERS', 'للسائقين') : t('FOR SERVICE PROVIDERS', 'لمقدمي الخدمات')}</span></div>
    <div className="partner-card-copy"><h3>{driver ? t('Your city. Your next opportunity.', 'مدينتك. فرصتك القادمة.') : t('Your skills deserve more possibilities.', 'خبرتك تستحق فرصًا أكثر.')}</h3><p>{driver ? t('Earn with every completed ride. Connect with nearby riders and make the road ahead work for you.', 'اكسب من كل مشوار مكتمل. تواصل مع الركاب القريبين واجعل الطريق بداية لفرصك.') : t('From home repairs to everyday care, connect your expertise with customers who need it.', 'من إصلاحات المنزل إلى العناية اليومية، وصّل خبرتك للعملاء الذين يحتاجونها.')}</p>
    <div className="partner-tags"><span><Wallet size={14}/>{t('Earn with us', 'اكسب معنا')}</span><span><Smartphone size={14}/>{t('Your own partner app', 'تطبيق مخصص لك')}</span></div>
    <a className="partner-card-link" href={`/${ar ? 'ar' : 'en'}/${kind}/`}>{driver ? t('Explore driving with us', 'اكتشف فرص القيادة معنا') : t('Grow with OrderUp', 'طوّر أعمالك مع OrderUp')}<span><ArrowUpRight size={22}/></span></a></div>
   </article>;
  })}</div>
  <div className="partner-hub-note"><Gift size={18}/><span>{t('A little extra to look forward to. Explore partner bonuses and incentives when available.', 'مزايا إضافية تستحق الاهتمام. اكتشف مكافآت وحوافز الشركاء عند توفرها.')}</span></div>
 </div></section>;
}

export function PartnerPage({ar, kind}: {ar: boolean; kind: Partner}) {
 const t = (en: string, arabic: string) => pick(ar, en, arabic);
 const driver = kind === 'driver'; const Icon = driver ? CarFront : Wrench;
 const app = driver ? 'OrderUp Driver' : 'OrderUp Service Providers';
 const benefits = driver ? [
  [Clock3, t('Make room for your goals', 'فرص تناسب أهدافك'), t('Explore driving as an additional earning opportunity alongside your everyday commitments.', 'اكتشف القيادة كفرصة دخل إضافية إلى جانب التزاماتك اليومية.')],
  [MapPin, t('Connect locally', 'تواصل مع القريبين'), t('Connect with people looking for a ride around you. Your knowledge of the city can make a difference.', 'تواصل مع الباحثين عن مشوار بالقرب منك. معرفتك بالمدينة تصنع فرقًا.')],
  [Smartphone, t('Keep work connected', 'عملك في مكان واحد'), t('Use the dedicated driver app to connect with ride opportunities and manage your driving experience.', 'استخدم تطبيق السائق المخصص للتواصل مع فرص المشاوير وإدارة تجربتك.')],
 ] as const : [
  [MapPin, t('Meet your next customer', 'تعرّف على عميلك القادم'), t('Connect with people nearby who are looking for the services you offer.', 'تواصل مع الأشخاص القريبين الذين يبحثون عن الخدمات التي تقدمها.')],
  [Wrench, t('Put your expertise to work', 'حوّل خبرتك إلى فرص'), t('Bring your experience in cleaning, repairs, installation or other supported home services.', 'قدّم خبرتك في التنظيف أو الإصلاحات أو التركيب أو الخدمات المنزلية المدعومة.')],
  [Smartphone, t('One app for your work', 'تطبيق واحد لأعمالك'), t('Manage your service opportunities through the dedicated OrderUp Service Providers app.', 'أدر فرص تقديم خدماتك من خلال تطبيق OrderUp Service Providers المخصص.')],
 ] as const;
 const steps = driver ? [
  [t('Get the driver app', 'حمّل تطبيق السائق'), t('Use the official Android or iOS link below when it becomes available.', 'استخدم رابط Android أو iOS الرسمي أدناه عند توفره.')],
  [t('Prepare your details', 'جهّز بياناتك'), t('Have your driving licence and vehicle information ready. Follow the app’s current registration requirements.', 'جهّز رخصة القيادة ومعلومات المركبة، واتبع متطلبات التسجيل الحالية في التطبيق.')],
  [t('Complete onboarding', 'أكمل خطوات الانضمام'), t('Submit the requested information and complete any required verification before taking rides.', 'قدّم المعلومات المطلوبة وأكمل التحقق اللازم قبل بدء المشاوير.')],
 ] : [
  [t('Get the provider app', 'حمّل تطبيق مقدم الخدمة'), t('Use the official Android or iOS link below when it becomes available.', 'استخدم رابط Android أو iOS الرسمي أدناه عند توفره.')],
  [t('Introduce your services', 'عرّف بخدماتك'), t('Prepare your service categories, experience and the areas you cover for registration.', 'جهّز فئات خدماتك وخبراتك والمناطق التي تغطيها للتسجيل.')],
  [t('Complete onboarding', 'أكمل خطوات الانضمام'), t('Follow the app’s requirements and complete any requested professional or business verification.', 'اتبع متطلبات التطبيق وأكمل أي تحقق مهني أو تجاري مطلوب.')],
 ];
 const faqs = [
  [t('How do I start earning?', 'كيف أبدأ بتحقيق الدخل؟'), driver ? t('Start by joining through the official driver app once its download links are available. Complete the required onboarding before accepting rides. Earnings depend on completed rides and the applicable app terms.', 'ابدأ بالانضمام عبر تطبيق السائق الرسمي عند توفر روابط تحميله. أكمل خطوات الانضمام المطلوبة قبل قبول المشاوير. يعتمد الدخل على المشاوير المكتملة وشروط التطبيق المعمول بها.') : t('Join through the official provider app once its download links are available, add your service information and complete the required onboarding. Earnings depend on completed services and the applicable app terms.', 'انضم عبر تطبيق مقدم الخدمة الرسمي عند توفر روابط تحميله، وأضف معلومات خدماتك وأكمل خطوات الانضمام. يعتمد الدخل على الخدمات المكتملة وشروط التطبيق المعمول بها.')],
  [t('Are bonuses guaranteed?', 'هل المكافآت مضمونة؟'), t('No. Bonuses are available only when a specific offer is announced. Check the offer’s eligibility, dates and completion conditions before taking part. No fixed bonus or income amount is promised here.', 'لا. تتوفر المكافآت فقط عند الإعلان عن عرض محدد. راجع شروط الأهلية والمواعيد ومتطلبات الإنجاز قبل المشاركة. لا تتضمن هذه الصفحة وعدًا بمكافأة أو دخل محدد.')],
  [t('What do I need to join?', 'ما الذي أحتاجه للانضمام؟'), driver ? t('Prepare your contact details, driving licence and vehicle information. The official registration flow will confirm the full requirements and supported locations.', 'جهّز بيانات التواصل ورخصة القيادة ومعلومات المركبة. ستوضح خطوات التسجيل الرسمية جميع المتطلبات والمناطق المدعومة.') : t('Prepare your contact details, service categories and relevant professional or business information. The official registration flow will confirm the full requirements and supported locations.', 'جهّز بيانات التواصل وفئات الخدمات والمعلومات المهنية أو التجارية ذات الصلة. ستوضح خطوات التسجيل الرسمية جميع المتطلبات والمناطق المدعومة.')],
  [t('Where can I download the app?', 'أين يمكنني تحميل التطبيق؟'), t('The Android and iOS options below will link to the official stores once the links are available. Please check back here for the latest download availability.', 'سترتبط خيارات Android وiOS أدناه بالمتاجر الرسمية عند توفر الروابط. يرجى العودة إلى هذه الصفحة لمعرفة آخر تحديثات التحميل.')],
 ];
 return <><Navbar ar={ar} page={kind}/><main id="main" className={`partner-page ${kind}`}>
  <section className="partner-hero"><div className="container">
   <a className="partner-back" href={`/${ar ? 'ar' : 'en'}/#drivers`}>{t('OrderUp', 'OrderUp')}<span>/</span>{t('Partners', 'الشركاء')}<span>/</span>{driver ? t('Drivers', 'السائقون') : t('Service providers', 'مقدمو الخدمات')}</a>
   <div className="partner-hero-grid"><div className="partner-hero-copy"><div className="eyebrow"><Icon size={18}/>{driver ? t('DRIVE WITH ORDERUP', 'قد مع OrderUp') : t('BUILD WITH ORDERUP', 'طوّر أعمالك مع OrderUp')}</div><h1>{driver ? t('Your next turn.', 'خطوتك القادمة.') : t('Your expertise.', 'خبرتك.')}<br/><em>{driver ? t('More possibility.', 'فرص أكثر.') : t('More opportunity.', 'فرص أوسع.')}</em></h1><p>{driver ? t('Put your city knowledge to work. Connect with riders, earn from completed trips and take your next step with OrderUp Driver.', 'حوّل معرفتك بالمدينة إلى فرصة. تواصل مع الركاب واكسب من المشاوير المكتملة وابدأ خطوتك القادمة مع OrderUp Driver.') : t('You bring the skills. We help you connect. Find new service opportunities and build your next chapter with OrderUp.', 'أنت تقدم الخبرة، ونحن نساعدك على التواصل. اكتشف فرص خدمات جديدة وابدأ فصلًا جديدًا لأعمالك مع OrderUp.')}</p><div className="partner-hero-actions"><a className="button" href="#download">{t('Get the partner app', 'حمّل تطبيق الشريك')}<ArrowUpRight size={18}/></a><a className="text-button" href="#getting-started">{t('How to join', 'كيفية الانضمام')}<ArrowRight size={17}/></a></div><div className="partner-platform"><Smartphone size={15}/>{t('Android & iOS · Download links coming soon', 'Android وiOS · روابط التحميل قريبًا')}</div></div>
    <div className="partner-hero-visual"><Image src={driver ? '/images/driver-cover.webp' : '/images/home-service.webp'} alt={driver ? t('A driver beside a white car in Jeddah', 'سائق بجوار سيارة بيضاء في جدة') : t('A service professional repairing a kitchen fixture', 'فني خدمات يصلح تجهيزات المطبخ')} width={1440} height={960} priority sizes="(max-width: 800px) 100vw, 55vw"/><div className="partner-visual-caption"><span className="partner-caption-icon"><Icon size={25}/></span><div><small>{t('YOUR SKILLS. YOUR NEXT CHAPTER.', 'مهاراتك. خطوتك القادمة.')}</small><strong>{driver ? t('Make every journey count.', 'اجعل لكل مشوار قيمة.') : t('Good work opens doors.', 'العمل المتقن يفتح الفرص.')}</strong></div></div></div>
   </div>
  </div></section>
  <section className="partner-benefits"><div className="container">{benefits.map(([BenefitIcon,title,copy])=><article key={title}><BenefitIcon size={25} strokeWidth={1.6}/><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="section" id="earn"><div className="container partner-earn-grid"><div className="feature-copy"><div className="eyebrow">{t('EARN WITH US', 'اكسب معنا')}</div><h2>{t('Your effort.', 'جهدك.')}<br/><em>{t('New possibilities.', 'إمكانيات جديدة.')}</em></h2><p>{driver ? t('A new route to your goals starts with the work you do. Earn from completed rides and look out for eligible partner incentives when they are announced.', 'طريق جديد نحو أهدافك يبدأ بعملك. اكسب من المشاوير المكتملة وتابع حوافز الشركاء التي تنطبق عليك عند الإعلان عنها.') : t('Turn the services you provide into opportunities to earn. Connect with new customers and look out for eligible partner incentives when they are announced.', 'حوّل الخدمات التي تقدمها إلى فرص دخل. تواصل مع عملاء جدد وتابع حوافز الشركاء التي تنطبق عليك عند الإعلان عنها.')}</p><a className="inline-link" href="#getting-started">{t('Take your first step', 'ابدأ خطوتك الأولى')}<ArrowRight size={18}/></a></div>
   <div className="earning-panel"><div className="earning-panel-heading"><Wallet size={24}/><span>{t('OPPORTUNITY, BUILT AROUND YOU', 'فرص تتمحور حولك')}</span></div><article><span className="earning-number">01</span><div><h3>{driver ? t('Earn from completed rides', 'اكسب من المشاوير المكتملة') : t('Earn from completed services', 'اكسب من الخدمات المكتملة')}</h3><p>{t('Your earnings depend on the work you complete and the terms that apply in the app.', 'يعتمد دخلك على العمل الذي تنجزه والشروط المعمول بها في التطبيق.')}</p></div></article><article><span className="earning-number">02</span><div><h3>{t('Discover bonus opportunities', 'اكتشف فرص المكافآت')}</h3><p>{t('When an incentive is offered, review its requirements and work toward the qualifying goal.', 'عند طرح حافز، راجع متطلباته واعمل على تحقيق الهدف المؤهل له.')}</p></div></article><div className="bonus-callout"><Gift size={28}/><div><h3>{t('A little extra, when available.', 'مزايا إضافية، عند توفرها.')}</h3><p>{t('Confirmed bonus offers and eligibility details will appear here when announced.', 'ستُضاف عروض المكافآت المؤكدة وتفاصيل الأهلية هنا عند الإعلان عنها.')}</p><span>{t('Offers to be announced', 'سيُعلن عن العروض لاحقًا')}</span></div></div></div>
  </div></section>
  {!driver && <section className="provider-specialties"><div className="container"><div className="eyebrow">{t('THERE’S A PLACE FOR YOUR EXPERTISE', 'مكان لخبرتك')}</div><h2>{t('What do you do best?', 'ما مجال خبرتك؟')}</h2><div>{[['Cleaning','التنظيف'],['Plumbing','السباكة'],['Electrical work','الكهرباء'],['Maintenance','الصيانة'],['Installation','التركيب'],['Home repairs','إصلاحات المنزل'],['Carpentry','النجارة'],['Massage','المساج']].map(([en,arabic])=><span key={en}><Check size={16}/>{t(en,arabic)}</span>)}</div></div></section>}
  <section className="section partner-start" id="getting-started"><div className="container"><div className="section-heading"><div><div className="eyebrow">{t('A SIMPLE PLACE TO START', 'بداية بخطوات بسيطة')}</div><h2>{t('Your journey with us.', 'رحلتك معنا.')}</h2></div><p>{t('Get ready for your next opportunity. Final registration requirements are confirmed in the partner app.', 'استعد لفرصتك القادمة. يتم تأكيد متطلبات التسجيل النهائية في تطبيق الشريك.')}</p></div><div className="partner-steps">{steps.map(([title,copy],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="partner-steps-note"><BadgeCheck size={18}/>{t('Availability and eligibility depend on your location and the applicable partner requirements.', 'يعتمد التوفر والأهلية على موقعك ومتطلبات الشراكة المعمول بها.')}</div></div></section>
  <section className="partner-download" id="download"><div className="container partner-download-grid"><div><div className="eyebrow">{t('YOUR WORK. YOUR DEDICATED APP.', 'عملك. تطبيقك المخصص.')}</div><h2>{driver ? t('Meet your new', 'تعرّف على رفيق') : t('A new home', 'مساحة جديدة')}<br/>{driver ? t('driving companion.', 'مشاويرك الجديد.') : t('for your expertise.', 'لخبرتك.')}</h2><p>{driver ? t('Take the next step with OrderUp Driver. Your connection to ride opportunities, in your pocket.', 'ابدأ خطوتك القادمة مع OrderUp Driver. فرص المشاوير أقرب إليك، في جيبك.') : t('Bring your business to OrderUp Service Providers. Your connection to customers, wherever work takes you.', 'انضم بأعمالك إلى OrderUp Service Providers. تواصلك مع العملاء أينما يأخذك العمل.')}</p><StoreButtons ar={ar} audience={kind}/><p className="partner-download-note" id="download-info" tabIndex={-1}>{t('Official Android and iOS download links are coming soon. Registration details will be available with the app links.', 'روابط التحميل الرسمية لـ Android وiOS قريبًا. ستتوفر تفاصيل التسجيل مع روابط التطبيق.')}</p></div><div className="partner-app-identity"><div className="partner-app-logo"><Image src="/images/orderup-logo.png" alt="OrderUp" width={1329} height={405} sizes="230px"/></div><span className="partner-app-role"><Icon size={22}/>{driver ? t('DRIVER', 'السائق') : t('SERVICE PROVIDERS', 'مقدمو الخدمات')}</span><h3 dir="ltr">{app}</h3><p>{driver ? t('More opportunity on the road ahead.', 'فرص أكثر على الطريق.') : t('More connections for the work you do.', 'تواصل أوسع لأعمالك.')}</p><div className="partner-app-platforms"><span>Android</span><span>iOS</span></div></div></div></section>
  <section className="section partner-faq"><div className="container faq-grid"><div><div className="eyebrow">{t('A FEW THINGS TO KNOW', 'معلومات تهمك')}</div><h2>{t('Your questions,', 'أسئلتك،')}<br/>{t('answered.', 'وإجاباتها.')}</h2></div><div>{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div></div></section>
  <div className="container partner-switch"><Sparkles size={20}/><p>{driver ? t('Have a skill to share, too?', 'هل لديك خبرة تقدمها أيضًا؟') : t('Prefer the road ahead?', 'تفضّل فرص القيادة؟')}</p><a href={`/${ar ? 'ar' : 'en'}/${driver ? 'providers' : 'driver'}/`}>{driver ? t('Explore service partnerships', 'اكتشف شراكات الخدمات') : t('Explore driving with us', 'اكتشف فرص القيادة معنا')}<ArrowUpRight size={17}/></a></div>
 </main></>;
}
